=== ipeychev/liferay-portal/definitions/liferay-workflow-definition_7_4_0.xsd
<?xml version="1.0"?>

<xs:schema
	elementFormDefault="qualified"
	targetNamespace="urn:liferay.com:liferay-workflow_7.4.0"
	xmlns="urn:liferay.com:liferay-workflow_7.4.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" />
	<xs:complexType abstract="true" name="abstract-notification-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:element name="template" type="xs:string" />
			<xs:element name="template-language" type="template-language-type" />
			<xs:element maxOccurs="unbounded" name="notification-type" type="notification-transport-type" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType abstract="true" name="abstract-timer-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:element name="delay" type="time-delay-complex-type" />
			<xs:element minOccurs="0" name="recurrence" type="time-delay-complex-type" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType abstract="true" name="abstract-workflow-node-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:element minOccurs="0" name="metadata" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="action-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:choice maxOccurs="1" minOccurs="1">
				<xs:sequence>
					<xs:element name="script" type="xs:string" />
					<xs:element name="script-language" type="script-language-type" />
					<xs:element minOccurs="0" name="script-required-contexts" type="xs:string" />
				</xs:sequence>
				<xs:element name="status" type="xs:int" />
			</xs:choice>
			<xs:element minOccurs="0" name="priority" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="action-timer-workflow-node-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-workflow-node-complex-type">
				<xs:sequence>
					<xs:element minOccurs="0" name="actions">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded" minOccurs="0">
								<xs:group ref="actions-group" />
							</xs:choice>
						</xs:complexType>
					</xs:element>
					<xs:element minOccurs="0" name="timers">
						<xs:complexType>
							<xs:sequence>
								<xs:element maxOccurs="unbounded" name="timer" type="timer-complex-type" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="notification-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-notification-complex-type">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="recipients" type="recipients-complex-type" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="recipients-complex-type">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="address" type="email-address-type" />
			<xs:element minOccurs="0" name="roles">
				<xs:complexType>
					<xs:choice minOccurs="0">
						<xs:element maxOccurs="unbounded" name="role" type="role-complex-type" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element maxOccurs="unbounded" minOccurs="0" name="scripted-recipient" type="script-complex-type" />
			<xs:element maxOccurs="unbounded" minOccurs="0" name="user" type="user-complex-type" />
		</xs:sequence>
		<xs:attribute default="to" name="receptionType" type="notification-reception-type" />
	</xs:complexType>
	<xs:complexType name="role-complex-type">
		<xs:sequence>
			<xs:choice>
				<xs:element minOccurs="0" name="role-id" type="xs:long" />
				<xs:sequence>
					<xs:element default="regular" minOccurs="0" name="role-type" type="role-type" />
					<xs:element minOccurs="0" name="name" type="xs:string" />
					<xs:element default="true" minOccurs="0" name="auto-create" type="xs:boolean" />
				</xs:sequence>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="script-complex-type">
		<xs:sequence>
			<xs:element name="script" type="xs:string" />
			<xs:element name="script-language" type="script-language-type" />
			<xs:element minOccurs="0" name="script-required-contexts" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="task-form-complex-type">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element minOccurs="0" name="description" type="xs:string" />
			<xs:choice maxOccurs="1">
				<xs:element name="form-definition" type="xs:string" />
				<xs:element name="form-reference">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="company-id" type="xs:long" />
							<xs:element name="form-id" type="xs:long" />
							<xs:element name="form-uuid" type="xs:string" />
							<xs:element name="group-id" type="xs:long" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:element minOccurs="0" name="metadata" type="xs:string" />
			<xs:element name="priority" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="task-notification-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-notification-complex-type">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="recipients" type="task-recipients-complex-type" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="task-recipients-complex-type">
		<xs:complexContent>
			<xs:extension base="recipients-complex-type">
				<xs:sequence>
					<xs:element maxOccurs="1" minOccurs="0" name="assignees">
						<xs:complexType />
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="task-timer-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-timer-complex-type">
				<xs:sequence>
					<xs:element default="false" minOccurs="0" name="blocking" type="xs:boolean" />
					<xs:element name="timer-actions">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded">
								<xs:group ref="task-timer-actions-group" />
							</xs:choice>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="time-delay-complex-type">
		<xs:sequence>
			<xs:element name="duration" type="xs:double" />
			<xs:element name="scale" type="time-scale-type" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="timer-complex-type">
		<xs:complexContent>
			<xs:extension base="abstract-timer-complex-type">
				<xs:sequence>
					<xs:element minOccurs="0" name="timer-actions">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded">
								<xs:group ref="timer-actions-group" />
							</xs:choice>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="user-complex-type">
		<xs:choice>
			<xs:element minOccurs="0" name="user-id" type="xs:long" />
			<xs:element minOccurs="0" name="screen-name" type="xs:string" />
			<xs:element minOccurs="0" name="email-address" type="email-address-type" />
		</xs:choice>
	</xs:complexType>
	<xs:element name="ai-decision">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="abstract-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element minOccurs="0" name="input-variables" type="xs:string" />
						<xs:element minOccurs="0" name="output-variables" type="xs:string" />
						<xs:element name="prompt" type="xs:string" />
						<xs:element minOccurs="0" name="rag" type="xs:string" />
						<xs:element minOccurs="0" name="tools" type="xs:string" />
						<xs:element minOccurs="0" ref="transitions" />
						<xs:element name="user-message" type="xs:string" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="condition">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element name="script" type="xs:string" />
						<xs:element name="script-language" type="script-language-type" />
						<xs:element minOccurs="0" name="script-required-contexts" type="xs:string" />
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fork">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="join">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="join-xor">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="labels">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="label">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="language-id" type="xs:string" use="required" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="llm">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="abstract-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element minOccurs="0" name="input-variables" type="xs:string" />
						<xs:element minOccurs="0" name="output-variables" type="xs:string" />
						<xs:element name="prompt" type="xs:string" />
						<xs:element minOccurs="0" name="rag" type="xs:string" />
						<xs:element minOccurs="0" name="tools" type="xs:string" />
						<xs:element minOccurs="0" ref="transitions" />
						<xs:element name="user-message" type="xs:string" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tool">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="abstract-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element name="tool-name" type="xs:string" />
						<xs:element minOccurs="0" name="input-variables" type="xs:string" />
						<xs:element minOccurs="0" name="output-variables" type="xs:string" />
						<xs:element minOccurs="0" ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="state">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="action-timer-workflow-node-complex-type">
					<xs:sequence>
						<xs:element default="false" minOccurs="0" name="initial" type="xs:boolean" />
						<xs:element minOccurs="0" ref="labels" />
						<xs:element minOccurs="0" ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="task">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="abstract-workflow-node-complex-type">
					<xs:sequence>
						<xs:element minOccurs="0" name="actions">
							<xs:complexType>
								<xs:choice>
									<xs:group maxOccurs="unbounded" ref="task-actions-group" />
								</xs:choice>
							</xs:complexType>
						</xs:element>
						<xs:element name="assignments">
							<xs:complexType>
								<xs:choice>
									<xs:group ref="assignments-group" />
								</xs:choice>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" ref="labels" />
						<xs:element minOccurs="0" name="task-forms">
							<xs:complexType>
								<xs:sequence>
									<xs:element maxOccurs="unbounded" name="task-form" type="task-form-complex-type" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" name="task-timers">
							<xs:complexType>
								<xs:sequence>
									<xs:element maxOccurs="unbounded" name="task-timer" type="task-timer-complex-type" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element ref="transitions" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="transitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="transition">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" ref="labels" />
							<xs:element name="name" type="xs:string" />
							<xs:element name="target" type="xs:string" />
							<xs:element default="true" minOccurs="0" name="default" type="xs:boolean" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="workflow-definition">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="name" type="xs:string" />
				<xs:element minOccurs="0" name="description" type="xs:string" />
				<xs:element minOccurs="0" name="version" type="xs:int" />
				<xs:group maxOccurs="unbounded" ref="nodes-group" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="actions-group">
		<xs:choice>
			<xs:element name="action">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="action-complex-type">
							<xs:sequence>
								<xs:element name="execution-type" type="execution-type" />
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="notification">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="notification-complex-type">
							<xs:sequence>
								<xs:element name="execution-type" type="execution-type" />
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="assignments-group">
		<xs:choice>
			<xs:element name="resource-actions">
				<xs:complexType>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" name="resource-action" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="roles">
				<xs:complexType>
					<xs:choice minOccurs="0">
						<xs:element maxOccurs="unbounded" name="role" type="role-complex-type" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="scripted-assignment" type="script-complex-type" />
			<xs:element maxOccurs="unbounded" minOccurs="0" name="user" type="user-complex-type" />
		</xs:choice>
	</xs:group>
	<xs:group name="nodes-group">
		<xs:choice>
			<xs:element ref="ai-decision" />
			<xs:element ref="condition" />
			<xs:element ref="fork" />
			<xs:element ref="join" />
			<xs:element ref="join-xor" />
			<xs:element ref="llm" />
			<xs:element ref="state" />
			<xs:element ref="task" />
			<xs:element ref="tool" />
		</xs:choice>
	</xs:group>
	<xs:group name="task-actions-group">
		<xs:choice>
			<xs:element name="action">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="action-complex-type">
							<xs:sequence>
								<xs:element name="execution-type" type="task-execution-type" />
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="notification">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="task-notification-complex-type">
							<xs:sequence>
								<xs:element name="execution-type" type="task-execution-type" />
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="task-timer-actions-group">
		<xs:choice>
			<xs:element name="timer-action" type="action-complex-type" />
			<xs:element name="timer-notification" type="task-notification-complex-type" />
			<xs:element minOccurs="0" name="reassignments">
				<xs:complexType>
					<xs:choice>
						<xs:group ref="assignments-group" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="timer-actions-group">
		<xs:choice>
			<xs:element name="timer-action" type="action-complex-type" />
			<xs:element name="timer-notification" type="notification-complex-type" />
		</xs:choice>
	</xs:group>
	<xs:simpleType name="email-address-type">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^\.]+\..+" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="execution-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="onEntry" />
			<xs:enumeration value="onExit" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="notification-transport-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="email" />
			<xs:enumeration value="im" />
			<xs:enumeration value="private-message" />
			<xs:enumeration value="push-notification" />
			<xs:enumeration value="user-notification" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="notification-reception-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bcc" />
			<xs:enumeration value="cc" />
			<xs:enumeration value="to" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="role-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="account" />
			<xs:enumeration value="depot" />
			<xs:enumeration value="organization" />
			<xs:enumeration value="regular" />
			<xs:enumeration value="site" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="script-language-type">
		<xs:restriction base="xs:string">
			<xs:pattern value="(drl|function#[a-z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*|groovy|java)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="task-execution-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="onAssignment" />
			<xs:enumeration value="onEntry" />
			<xs:enumeration value="onExit" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="template-language-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="freemarker" />
			<xs:enumeration value="text" />
			<xs:enumeration value="velocity" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="time-scale-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="second" />
			<xs:enumeration value="minute" />
			<xs:enumeration value="hour" />
			<xs:enumeration value="day" />
			<xs:enumeration value="week" />
			<xs:enumeration value="month" />
			<xs:enumeration value="year" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ipeychev/liferay-portal/modules/dxp/apps/ai-hub/ai-hub-site-initializer/src/main/resources/site-initializer/workflow-definitions/categorization-intent-workflow-definition/workflow-definition.xml
<?xml version="1.0"?>

<workflow-definition
	xmlns="urn:liferay.com:liferay-workflow_7.4.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:liferay.com:liferay-workflow_7.4.0 http://www.liferay.com/dtd/liferay-workflow-definition_7_4_0.xsd"
>
	<name>Categorization Intent</name>
	<version>1</version>
	<llm>
		<name>categorizationIntent</name>
		<metadata>
			<![CDATA[
				{
					"xy": [
						276,
						242
					]
				}
			]]>
		</metadata>
		<labels>
			<label language-id="en_US">
				Categorization Intent
			</label>
		</labels>
		<input-variables>
			<![CDATA[
				[
					{
						"name": "message",
						"type": "string"
					}
				]
			]]>
		</input-variables>
		<output-variables>
			<![CDATA[
				[
					{
						"name": "intent",
						"type": "string"
					}
				]
			]]>
		</output-variables>
		<prompt>
			<![CDATA[# Role

You decide whether a user message is purely a request to categorize and/or tag the content the user is currently editing. The message may be written in any language. You never categorize or tag anything yourself; you only report the detected intent as structured data.

# Inputs

- message: the raw text the user typed into the assistant chat.

# Hard rules

- "categorize" means assigning the content to existing categories or vocabularies. "tag" means attaching free form keywords. A message may ask for one, both, or neither.
- Set passthrough to true and return an empty actions array whenever the message is anything other than a pure request to categorize and/or tag. This includes questions ("what tags fit this?"), removals ("remove the tag travel"), requests that combine categorization with unrelated work ("tag this and shorten the intro"), and anything ambiguous. A missed request is harmless because the message simply continues to the normal assistant, but a wrong match hijacks the conversation, so prefer passthrough whenever in doubt.
- When the message is a pure request to categorize and/or tag, set passthrough to false and return one action per requested operation.
- For each action, set agent to "categorize" or "tag". Copy any explicitly named categories or tags verbatim into targets as separate strings; when the message names none, return an empty targets array. Copy an explicitly requested number into count; when the message states no number, set count to null.
- When the message requests both categorizing and tagging, return the categorize action before the tag action.

# Output policy

- Output a SINGLE raw JSON object and nothing else.
- DO NOT wrap the JSON in markdown fences (no ```json, no ```).
- DO NOT add prose, commentary, or trailing text.
- Shape:

{
	"actions": [
		{
			"agent": "categorize" | "tag",
			"count": <number or null>,
			"targets": ["<string>"]
		}
	],
	"passthrough": <boolean>
}]]>
		</prompt>
		<tools>
			<![CDATA[[]]]>
		</tools>
		<transitions>
			<transition>
				<labels>
					<label language-id="en_US">
						End
					</label>
				</labels>
				<name>end</name>
				<target>end</target>
				<default>true</default>
			</transition>
		</transitions>
		<user-message>
			<![CDATA[{{message}}]]>
		</user-message>
	</llm>
	<state>
		<name>start</name>
		<metadata>
			<![CDATA[
				{
					"xy": [
						273,
						25
					]
				}
			]]>
		</metadata>
		<initial>true</initial>
		<labels>
			<label language-id="en_US">
				Start
			</label>
		</labels>
		<transitions>
			<transition>
				<labels>
					<label language-id="en_US">
						Categorization Intent
					</label>
				</labels>
				<name>categorizationIntent</name>
				<target>categorizationIntent</target>
				<default>true</default>
			</transition>
		</transitions>
	</state>
	<state>
		<name>end</name>
		<metadata>
			<![CDATA[
				{
					"terminal": true,
					"xy": [
						277,
						459
					]
				}
			]]>
		</metadata>
		<labels>
			<label language-id="en_US">
				End
			</label>
		</labels>
	</state>
</workflow-definition>

=== ipeychev/liferay-portal/modules/dxp/apps/ai-hub/ai-hub-site-initializer/src/main/resources/site-initializer/workflow-definitions/cms-blog-builder-workflow-definition/workflow-definition.xml
<?xml version="1.0"?>

<workflow-definition
	xmlns="urn:liferay.com:liferay-workflow_7.4.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:liferay.com:liferay-workflow_7.4.0 http://www.liferay.com/dtd/liferay-workflow-definition_7_4_0.xsd"
>
	<name>CMS Blog Builder</name>
	<version>1</version>
	<llm>
		<name>cmsBlogBuilder</name>
		<metadata>
			<![CDATA[
				{
					"xy": [
						276,
						242
					]
				}
			]]>
		</metadata>
		<labels>
			<label language-id="en_US">
				CMS Blog Builder
			</label>
		</labels>
		<input-variables>
			<![CDATA[
[
	{
		"name": "request",
		"type": "string"
	}
]
]]>
		</input-variables>
		<output-variables>
			<![CDATA[
[
	{
		"name": "response",
		"type": "string"
	}
]
]]>
		</output-variables>
		<prompt>
			<![CDATA[# Role

You are a CMS blog-builder for Liferay. You receive a **natural-language request** (e.g. "Create a blog with the subject Agentic Systems" or "Create 7 blogs about birds") and you produce a JSON array of CMSBlog request bodies. Each element of the array is one blog.

If the request specifies N blogs, emit exactly N items. If the count is not specified, emit a single-item array.

# Required blog shape (per array element)

{
	"externalReferenceCode": "<BLOG_ERC>",
	"title": "<same value as title_i18n.en_US>",
	"title_i18n": {"en_US": "..."},
	"subtitle": "...",
	"subtitle_i18n": {"en_US": "..."},
	"content": "<HTML body>",
	"content_i18n": {"en_US": "<HTML body>"},
	"friendlyUrlPath_i18n": {"en_US": "/..."},
	"keywords": ["...", "..."]
}

Hard rules:
- The top-level output is ALWAYS a JSON array, even when there is only one blog.
- `title` and `title_i18n` are REQUIRED. Always emit both, and keep `title` equal to `title_i18n.en_US`.
- `content` is plain HTML (paragraphs, headings, lists). Keep it short — 2–4 paragraphs unless asked otherwise.
- When both `content` and `content_i18n.en_US` are emitted, they MUST be identical. Same rule for `subtitle` / `subtitle_i18n.en_US`.
- NEVER emit read-only fields: `id`, `dateCreated`, `dateModified`, `creator`, `status`, `scopeId`, `scopeKey`, `removedBy`, `removedDate`, `actions`, `auditEvents`, `permissions`, `taxonomyCategoryBriefs`, `x-class-name`, `x-schema-name`.
- `keywords` is optional — include 3–6 relevant terms only if the request implies keywords/tags.
- Locale keys use underscore: `en_US` (not `en-US`).
- Every `externalReferenceCode` in the array MUST be unique.

# Naming scheme

- `externalReferenceCode`: slugify the title (lowercase, hyphen-separated, ASCII only). Example: "Agentic Systems in Liferay" → `agentic-systems-in-liferay`.
- `friendlyUrlPath_i18n.en_US`: `/` + ERC. Example: `/agentic-systems-in-liferay`.

# Worked example

## Input: "Create 2 blogs about birds"

Output:
[
	{
		"externalReferenceCode": "the-wonderful-world-of-birds",
		"title": "The Wonderful World of Birds",
		"title_i18n": {"en_US": "The Wonderful World of Birds"},
		"subtitle": "Discover the fascinating diversity and beauty of our feathered friends.",
		"subtitle_i18n": {"en_US": "Discover the fascinating diversity and beauty of our feathered friends."},
		"content": "<p>Birds are a group of warm-blooded vertebrates constituting the class Aves...</p>",
		"content_i18n": {"en_US": "<p>Birds are a group of warm-blooded vertebrates constituting the class Aves...</p>"},
		"friendlyUrlPath_i18n": {"en_US": "/the-wonderful-world-of-birds"},
		"keywords": ["birds", "avian", "birdwatching", "nature", "ornithology"]
	},
	{
		"externalReferenceCode": "the-importance-of-bird-conservation",
		"title": "The Importance of Bird Conservation",
		"title_i18n": {"en_US": "The Importance of Bird Conservation"},
		"subtitle": "Why protecting bird populations is crucial for ecosystem health.",
		"subtitle_i18n": {"en_US": "Why protecting bird populations is crucial for ecosystem health."},
		"content": "<p>Birds are more than just beautiful creatures; they are essential indicators of environmental health...</p>",
		"content_i18n": {"en_US": "<p>Birds are more than just beautiful creatures; they are essential indicators of environmental health...</p>"},
		"friendlyUrlPath_i18n": {"en_US": "/the-importance-of-bird-conservation"},
		"keywords": ["birds", "conservation", "ecology", "environment", "wildlife"]
	}
]

# Output policy

- After producing the JSON array of CMSBlog bodies matching the schema above, call the `addItems` tool with `items` set to the full JSON array serialized as a single JSON string.
- The tool's return value is the agent's final answer. Emit it VERBATIM — no surrounding prose, no commentary, no markdown fences.
- Never invent fields not listed in the schema. If the request can't be fulfilled, do NOT call the tool — output {"_error": "<reason>"} as plain text instead.]]>
		</prompt>
		<tools>
			<![CDATA[
				[
					{
						"name": "cmsBlog"
					}
				]
			]]>
		</tools>
		<transitions>
			<transition>
				<labels>
					<label language-id="en_US">
						End
					</label>
				</labels>
				<name>end</name>
				<target>end</target>
				<default>true</default>
			</transition>
		</transitions>
		<user-message>
			<![CDATA[Request: {{request}}]]>
		</user-message>
	</llm>
	<state>
		<name>start</name>
		<metadata>
			<![CDATA[
				{
					"xy": [
						273,
						25
					]
				}
			]]>
		</metadata>
		<initial>true</initial>
		<labels>
			<label language-id="en_US">
				Start
			</label>
		</labels>
		<transitions>
			<transition>
				<labels>
					<label language-id="en_US">
						CMS Blog Builder
					</label>
				</labels>
				<name>cmsBlogBuilder</name>
				<target>cmsBlogBuilder</target>
				<default>true</default>
			</transition>
		</transitions>
	</state>
	<state>
		<name>end</name>
		<metadata>
			<![CDATA[
				{
					"terminal": true,
					"xy": [
						277,
						459
					]
				}
			]]>
		</metadata>
		<labels>
			<label language-id="en_US">
				End
			</label>
		</labels>
	</state>
</workflow-definition>
